name: Discord Status

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Discord Status
        uses: Sniddl/discord-activity@v1
        with:
          discord_id: 793263849091760128
          github_token: ${{ secrets.GITHUB_TOKEN }}