name: System Log

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Log
        run: |
          LOG=$(cat <<EOF
[ BOOT SEQUENCE ]

Commits      :: $(git rev-list --count HEAD)
Last Update  :: $(date)
Status       :: RUNNING
EOF
          )

          awk '/<!--SYSTEM_LOG_START-->/{print;print "```bash\n"ENVIRON["LOG"]"\n```";next}1' README.md > temp.md
          mv temp.md README.md

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "update system log" || exit 0
          git push